### ISSUE TITLE
Support IPv6.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [JagandeepBrar/package-wake-on-lan#4]
*	https://github.com/herzhenr/simple-wake-on-lan/issues/7#issuecomment-1694732573
*	https://github.com/herzhenr/simple-wake-on-lan/issues/4#issuecomment-1694732083

**Comment by jagandeepbrar** [comment]
This will require a major versioning with some breaking changes, however should be easy to add and I'll try to get to this soon!

**Comment by jagandeepbrar** [comment]
IPv6 addresses are now supported in v4.0.0.
