### ISSUE TITLE
Support SecureOn authentication.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [JagandeepBrar/package-wake-on-lan#5]
https://github.com/herzhenr/simple-wake-on-lan/issues/6#issuecomment-1694725013

**Comment by jagandeepbrar** [comment]
This should also be simple enough to add but I also do not have any devices that support this functionality, however the specification seems very simple (adding an additional 6 bytes to the end of the magic packet).

I'll get this included alongside the IPv6 support version :)

**Comment by jagandeepbrar** [comment]
This has been added with the release of v4.1.0.
